services:
  # NGINX reverse proxy to allow multiple web containers to be accessed on port 80
  # via localhost or hostname
  # See [containers/nginx_reverse_proxy/README.md](./containers/nginx_reverse_proxy/README.md)
  frontend:
    build:
      context: "./containers/frontend/"
    depends_on:
      - hotstart_web
    expose:
      - 80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - dsfrontend
      - dsbackend
    restart: unless-stopped

  # MySQL server Can be connected via host IP and port 3306 for admin by programs like SQLyog
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_USER: user
      MYSQL_PASSWORD: "${DB_ROOT_PASSWORD}"
    expose:
      - 3306
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
#     - ./db_auto_import/:/docker-entrypoint-initdb.d
    networks:
      - dsbackend
    restart: unless-stopped

  hotstart_php:
    depends_on:
      - mysql
    expose:
      - 9000
    build:
      ssh:
        - default
      context: "./containers/ss4_php81/"
      args:
        PHP_VERSION: 8.1
        PHP_INI: ${PHP_INI}
        PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
        fpm_uid: "${FPM_UID}"
        fpm_gid: "${FPM_GID}"
        app_dir: /var/www/html/app
        pm_max_children: 10
    environment:
      PHP_OPCACHE_VALIDATE_TIMESTAMPS: 1
      PHP_IDE_CONFIG: ${PHP_IDE_CONFIG}
      SS_DATABASE_SERVER: mysql
      SS_DATABASE_USERNAME: root
      SS_DATABASE_PASSWORD: ${DB_ROOT_PASSWORD}
      SS_DATABASE_NAME: hotstart
    working_dir: /var/www/html/app
    networks:
      - dsbackend
    volumes:
      - ${HOTSTART_LOCAL_WORKDIR}/:/var/www/html/app
    restart: unless-stopped

  hotstart_web:
    build:
      context: "./containers/nginx_reverse_proxy/"
    depends_on:
      - hotstart_php
    networks:
      - dsbackend
    expose:
      - 80
    ports:
      - 8085:80
    environment:
      - VIRTUAL_HOST=${HOTSTART_LOCAL_DOMAIN}
      - NGINX_PORT=80
      - DOCUMENT_ROOT=/var/www/html/app/public
      - NGINX_FASTCGI_TARGET=hotstart_php:9000
      - NGINX_SERVER_NAME=${HOTSTART_LOCAL_DOMAIN}
    volumes:
      - ./configs/php81_ss4/nginx/:/etc/nginx/templates
      - ${HOTSTART_LOCAL_WORKDIR}/:/var/www/html/app
    restart: always

networks:
  dsfrontend:
  dsbackend:
volumes:
  data:
  mysql_data:
